### ISSUE TITLE
Only first transaction is getting operation name assigned

### ISSUE THREAD

**Issue by Whassup** [newrelic/newrelic-node-apollo-server-plugin#196] opened 2022-04-22 04:08 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
After this change was added https://github.com/newrelic/newrelic-node-apollo-server-plugin/pull/184/files

I noticed that our transaction names all became `WebTransaction/Expressjs/POST//*`

Where as before each transaction names was set to specific operation being called e.g `WebTransaction/Expressjs/POST//query/MyAwesomeQuery`

For now I have locked our version to 1.2.1 to resolve this issue.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

For every transaction the operation name if available should be assigned.

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

1. Added a console.log to `validationDidStart` hook to see when that hook would run.

2. Queried graphql api

3. Noticed transaction name is set and  `validationDidStart` hook ran as expected

4. Queried graphql api again with same query.

5.  Transaction names get set as `WebTransaction/Expressjs/POST//*` and  `validationDidStart`  hook did not run.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: v16.14.2
Operating System and version: node:16.14.2-slim docker image

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

Looking at the apoolo docs for`validationdidstart` https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference#validationdidstart - it mentions

| Like parsingDidStart, this event does not fire if a request's document is already available in Apollo Server's cache (only successfully validated documents are cached by Apollo Server).

Which means it wont run for every request.

`executiondidstart` may be a better hook to set transaction name https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference#executiondidstart

**Comment by coreyarnold** [comment] 2022-04-22 05:49
@Whassup Thanks for reporting this issue! We will take a look and see about reproducing the issue so we can get those operations named more specifically again.

**Comment by bizob2828** [comment] 2022-04-25 15:29
@Whassup I think this is a duplicate of #189.  We're hoping to hop on it soon and get addressed.  Sorry for the troubles.

**Comment by bizob2828** [comment] 2022-04-27 20:32
@Whassup I just release version 1.3.0, it should fix the issue you have decribed.

**Closed by bizob2828** 2022-04-27 20:32 UTC
Labels: bug
