### ISSUE TITLE
Generic POST//graphql appears after running web server for a while

### ISSUE THREAD

**Issue by amloelxer** [newrelic/newrelic-node-apollo-server-plugin#117] opened 2021-07-14 21:59 UTC
## Description

Hey all, I'm running into a weird issue and was wondering if this is the right place to ask. A couple days ago, I integrated this plugin with our new relic integration (we use Apollo Server with express). Everything appeared to be working, but I noticed that after our servers run for a couple hours, performance seems to "degrade" according to new relic. When I look at the top most time consuming transaction, I see that it's a generic `post` to `/graphql`. 

<img width="359" alt="perf-issues-screenshot" src="https://user-images.githubusercontent.com/5010246/125696416-3c3c3296-435d-4539-9e6c-735ad301c98f.png">

When I dive into the segment trace for this generic post, I see that it's the amalgamation of all our graphql resolvers (this continued for many more segments) 

<img width="886" alt="Screen Shot 2021-07-14 at 5 24 05 PM" src="https://user-images.githubusercontent.com/5010246/125696591-3745c23e-0a15-4ce5-b6e6-52fa80ffc564.png">

What I find even odder is that when we deploy and new code starts running on our servers, is that this generic post on our top most time consumings transactions completely goes away for a couple hours and then comes back. (Screenshot below from 30 mins after fresh deploy). 

<img width="367" alt="non-perf-issues-screenshot" src="https://user-images.githubusercontent.com/5010246/125696935-e4ff998f-00b5-4aa7-b6f4-deb17d40a872.png">

As far as I can tell, nothing in our code calls all the resolvers at the same time. So my question is, is this expected behavior? Are we doing something wrong on our side? If it is expected,  why wouldn't this new relic transaction have an end depth like all the others? Also if so, is there a way to ignore it if it's not actually affecting perf? My goal here is to figure out if this is actually a server perf issue and fix it or it ignore it depending on what I learn here. Many thanks in advance. 

- Alex

## Expected Behavior

Generic `post//graphql` to not show up in our new relic transactions and instead show each individual transaction. 

## Steps to Reproduce

Install new relic, use Apollo express, add this as a plugin (as far as I can tell). 

## Your Environment

newrelic version 6.13.2
newrelic/apollo-server-plugin version  0.3.0
Node Version v12.13.1
Running on [heroku stack 18](https://devcenter.heroku.com/articles/heroku-18-stack)

**Comment by carlo-808** [comment] 2021-07-14 22:41
Thank you for submitting this issue. I think that the `POST//graphql` transaction you are seeing represents the main entry point for your application's graphql requests. Our agent web framework instrumentation might be aggregating the graphql requests under the `POST//graphql` transaction.  What web framework are you using with `apollo-server`? What version of `apollo-server` are you running?

**Comment by amloelxer** [comment] 2021-07-15 14:40
> Thank you for submitting this issue. I think that the `POST//graphql` transaction you are seeing represents the main entry point for your application's graphql requests. Our agent web framework instrumentation might be aggregating the graphql requests under the `POST//graphql` transaction. What web framework are you using with `apollo-server`? What version of `apollo-server` are you running?

@carlo-808 apologies for not including this in my original post. 

Express version 4.17.1 
Apollo Server Core version 2.18.2
Apollo Server Express version 2.18.2 

So I'm assuming this aggregation is not expected behavior? Please let me know if there is any other information I can include.

**Comment by carlo-808** [comment] 2021-07-16 22:17
Thank for that added context @amloelxer . This aggregation is not expected behavior. Could you please provide us with a simple reproduction of your server setup? I would like to try and reproduce it. We don't need data models or anything like that. I think just some code around your Express/Apollo setup should help.

**Comment by amloelxer** [comment] 2021-07-19 20:59
@carlo-808 I have added a simple reproduction of our server setup which you can find [here](https://github.com/amloelxer/nr-graphql-env-repro). It's not exactly 1 to 1 (for example we use typescript for development), but the way we use Apollo / express / new relic and all the config should be very similar. Also I want to make clear that the `POST//graphql` transaction doesn't show up right away for us. It appears to take a couple hours of traffic without a deploy and then it shows up. Please let me know when you get any updates and if I can help you in anyway. Thank you for your time.

**Comment by carlo-808** [comment] 2021-07-21 21:31
Thanks @amloelxer I'll try out the repro in the next few days and get back to you!

**Comment by michaelgoin** [comment] 2021-07-21 21:34
@amloelxer We'll take a look at the repro but we may also want to go the [official support route](https://support.newrelic.com/) so our support team can help with triaging such as capturing logs (which may contain sensitive info), links to look at your data, etc.. You can start that process now or wait for me to take a look at the repro.

We will aggregate on purpose for queries that cannot be processed / fail the very first step of validation, but would not expect to be seeing resolvers grouped together.

Also, to eliminate one recent change that is unlikely to cause issues but could be related... can you test out `v0.2.0` of the plugin? I'm guessing the change introduced in 0.3.0 isn't the cause and its more an unexpected error case, but worth checking if it is that or another of the newer changes potentially causing problems.

**Comment by carlo-808** [comment] 2021-07-23 23:13
@amloelxer Thank you for the reproduction. I tried it out and let it run for a few hours and I'm not seeing a `POST//graphql` transaction. It could be that my test is too simple. I'm just posting one query periodically over a few hours. It looks like you are supporting graphql subscriptions with this server. Do you have any subscription connections happening when you notice the `POST//graphql` transaction grouping?

**Comment by amloelxer** [comment] 2021-07-26 14:34
@michaelgoin thanks for the info, if we don't figure it out soon I'll go that route. 

@carlo-808 to my knowledge we have subscriptions setup server side, but don't really consume them client side in any meaningful way. That being said, I wanted to run something by you. 

I've been playing around with timeouts on our server and see that when I set an express app level timeout using something like [this](http://expressjs.com/en/resources/middleware/timeout.html), it'll also get recorded as `POST//graphql`. Does the transaction name only get set at the very end of the transaction so that the deepest path of the request can be recorded? 

Consider the following scenario: 
1. Client makes graphql request to notoriously slow resolver 
2. Before the resolve returns the data, app timeout happens and client is automatically sent a 503. 

What would be the expected transaction name of this? 

My suspicion is that something like this is occurring to us and this weird aggregation is occurring. That being said, we don't have any timeouts on our app server right now (express defaults to 2 mins to the best of my knowledge), but I know the heroku router will automatically send a 503 after [30 seconds](https://devcenter.heroku.com/articles/request-timeout).

If this is the case, is there any harm in setting the transaction name manually in graphql context below? My hope is that we could manually set it, and then it'll be overwritten by the code in the plugin when it resolves. However if it does timeout, hopefully it'll at least have a more meaningful transaction name. For us, it's important that we can disambiguate it from the rest so that we at least have a starting place for diagnosing slowness at a more granular level. 

I'm not sure this will work out, but my thoughts were something like this: 

```
const apolloServer = new ApolloServer({
    plugins: [nrGraphQLPlugin],
    context: async ({ req, res }) => {
      const con = await contextHandler(req, res);
      if (process.env.NODE_ENV === 'production') {
        newrelic.setTransactionName(
          req.body?.operationName ?? 'undefinedOperation',
        );
        newrelic.addCustomAttribute('graphQLParams', JSON.stringify(req.body));
      }
```

Does this seem feasible?

**Comment by carlo-808** [comment] 2021-07-26 16:59
@amloelxer The final naming of the graphql transaction happens at the `willSendResponse` phase of the apollo request lifecycle, basically the end. If the timeout you mentioned is happening, it could potentially end the transaction prematurely and name everything under `POST//graphql`. You're solution should work, but you'll be overwriting the name which should be fine in your case. I'm going to experiment with the `connect-timeout` middleware you mentioned and see if I can reproduce the behavior.

**Comment by michaelgoin** [comment] 2021-07-26 17:13
It is worth noting if you set the custom name, our instrumentation will not overwrite it later like you hoped. We always treat customer set transaction names via the API as the highest priority for the name. So it can work as a stop gap but won't quite get the behavior you were hoping for. You can set this custom via the context, as long as we have state by then (we should) or via your own plugin.

**Comment by carlo-808** [comment] 2021-07-28 17:54
@amloelxer I was able to reproduce the `POST//graphql` transaction grouping using `connect-timeout`. However, I'm seeing errors if the timeout occurs before the resolvers are completed. Are you seeing errors on the apollo server side of things? In any case, with my test I'm seeing the timeout short circuiting our apollo plugin transaction naming. With recent changes to how we name transactions we can move naming earlier in the apollo request lifecycle. This may give you better insight into what queries are slow. We'll prioritize that work and close this issue out when that's completed.

**Comment by amloelxer** [comment] 2021-07-30 14:17
@carlo-808 that is great to hear, thanks for all of your and @michaelgoin 's help. I look forward to seeing the changes.  As for errors, do you mean something that occurs in new relic errors, or something that is logged in the `formatError` function when constructing the `ApolloServer`?

**Comment by carlo-808** [comment] 2021-08-05 22:27
@amloelxer I was seeing `ServiceUnavailableError: Response timeout` errors with my setup which get reported to New Relic. I'm curious what kind of errors you were seeing when running a query that takes longer than the server timeout.

**Comment by rr0214** [comment] 2021-09-15 20:13
Effort: Medium

**Comment by codingwithoutcomments** [comment] 2021-09-29 19:06
We are also seeing the same thing with our organization.  Looking forward to seeing a fix.

**Closed** 2022-03-22 18:23 UTC
Labels: bug, size: medium
