### ISSUE TITLE
TypeError: (0 , apollo_server_plugin_1.default) is not a function

### ISSUE THREAD

**Issue by DaveHellsmith** [newrelic/newrelic-node-apollo-server-plugin#213] opened 2022-09-04 14:02 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

I am getting the following error when trying to use this plugin in a NestJS project

```sh
      plugins: [createPlugin({})],
                            ^
TypeError: (0 , apollo_server_plugin_1.default) is not a function
```

Short snippet of how I am trying to add the plugin:

```ts
import createPlugin from '@newrelic/apollo-server-plugin';

// part of app module
GraphQLModule.forRoot<ApolloDriverConfig>({
  driver: ApolloDriver,
  autoSchemaFile: true,
  debug: process.env.NODE_ENV !== 'production',
  playground: false,
  plugins: [createPlugin({}), ApolloServerPluginLandingPageLocalDefault()],
```

My suspicion is that this has to do with `apollo-server-core` version mismatch, these are the `apollo` packages that I am running on my project

```sh
    "apollo-server-core": "^3.6.4",
    "apollo-server-express": "^3.6.4",
```

while this plugin is seemingly on version 2.

Could someone confirm my suspicion please? Also are there any plans to update the deps?

**Comment by bizob2828** [comment] 2022-09-06 15:50
@DaveHellsmith this plugin works on version 3.x.  What made you believe it's only supported on 2.x?  I do see #214 which I've already commented on.  You can see here it works fine on 3.x.

```
Folder: apollo-federation
	 * @apollo/subgraph(1): 2.1.1
	 * @apollo/gateway(1): 2.1.1
	 * @opentelemetry/api(1): 1.2.0
	 * apollo-server(1): 3.10.2
	 * graphql(1): 16.6.0
Folder: apollo-server-express
	 * apollo-server-express(2): 2.26.0, 3.10.2
	 * express(1): 4.17.1
	 * graphql(1): 15.8.0
Folder: apollo-server-fastify
	 * apollo-server-fastify(2): 2.26.0, 3.10.2
	 * fastify(1): 3.17.0
	 * graphql(1): 15.8.0
Folder: apollo-server-hapi
	 * apollo-server-hapi(1): 3.10.2
	 * @hapi/hapi(1): 20.2.2
Folder: apollo-server-koa
	 * apollo-server-koa(2): 2.26.0, 3.10.2
	 * graphql(1): 15.8.0
	 * koa(1): 2.13.4
Folder: apollo-server-lambda
	 * apollo-server-lambda(2): 2.26.0, 3.10.2
	 * graphql(1): 15.8.0
Folder: apollo-server
	 * apollo-server(2): 2.26.0, 3.10.2
	 * graphql(1): 15.8.0
```

I just imported the plugin and it exports the function properly

```js
import createPlugin from '@newrelic/apollo-server-plugin'
console.log(typeof createPlugin)
```

And you can see it's a function.

```sh
❯ node index.js
function
```

Is this code snippet above typescript or just javascript getting transpiled and/or bundled to work with Nest?

**Comment by DaveHellsmith** [comment] 2022-09-07 08:22
@bizob2828 it's typescript. 

The lockfile specified 2.x and usually when we had issues with apollo plugins it was due to the version mismatch, I am sorry for the ignorance =]

We did have to do a change though to make it work with nestjs, please see the changes in https://github.com/HearMeTeam/newrelic-node-apollo-server-plugin/pull/1/files

**Comment by bizob2828** [comment] 2022-09-07 13:21
Ok I'll try to reproduce. Looking at your PR, that shouldn't be necessary to get it working.

**Comment by bizob2828** [comment] 2022-09-07 15:56
Ok I can reproduce it.  It seems to be an issue with our defined type [here](https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/index.d.ts). PR pending

**Comment by bizob2828** [comment] 2022-09-07 16:07
@DaveHellsmith to fix your issue you will have to put `esModuleInterop: true` in your ts config file.  This was a change in typescript 2.7 that affected some people.  You can read more about the option [here](https://www.typescriptlang.org/tsconfig#esModuleInterop).  I put that in a nest project ts config and now it works just fine.  I'm going to close this issue

**Closed by bizob2828** 2022-09-07 16:07 UTC
Labels: bug, needs-triage
