### ISSUE TITLE
newrelic/esm-loader.mjs breaks Prisma types in ESM/Typescript instrumentation

### ISSUE THREAD

**Issue by clarkClaim** [newrelic/newrelic-node-apollo-server-plugin#245] opened 2023-04-18 19:19 UTC
## Goal
I would like to instrument an Apollo server, which has been set up according to Apollo v4's recommendation to follow ESM standards, as well as Prisma/Pothos.

## Description
Following the implementation instructions for ESM, the below error was reported.  This suggests that one of the files generated by Prisma is being treated as CommonJS.  

(i.e. after following the setup instructions for instrumenting an ESM application, existing production code was broken).

```
> core@1.0.0 dev
claim-core-1  | > node --experimental-loader newrelic/esm-loader.mjs dist/src/index.js
claim-core-1  | 
claim-core-1  | (node:505) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
claim-core-1  | (Use `node --trace-warnings ...` to show where the warning was created)
claim-core-1  | file:///core/dist/src/graphql/models/user/inputs.js:4
claim-core-1  | import { user_onboarding_status } from '@prisma/client';
claim-core-1  |          ^^^^^^^^^^^^^^^^^^^^^^
claim-core-1  | SyntaxError: Named export 'user_onboarding_status' not found. The requested module '@prisma/client' is a CommonJS module, which may not support all module.exports as named exports.
claim-core-1  | CommonJS modules can always be imported via the default export, for example using:
claim-core-1  | 
claim-core-1  | import pkg from '@prisma/client';
claim-core-1  | const { user_onboarding_status } = pkg;
claim-core-1  | 
claim-core-1  |     at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
claim-core-1  |     at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
claim-core-1  |     at async Promise.all (index 0)
claim-core-1  |     at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
claim-core-1  |     at async loadESM (node:internal/process/esm_loader:88:5)
claim-core-1  |     at async handleMainPromise (node:internal/modules/run_main:61:12)
claim-core-1 exited with code 1
```

## Expected Behavior
After instrumenting the application, I would expect that calls to the Apollo server would result in output to New Relic.

## Steps to Reproduce

1. Setup a Apollo server, using Prisma, ESM, and TypeScript
2. Instrument, following ESM instructions

## Your Environment

package.json
```
  "type": "module",
  "scripts": {
    "build": "npx prisma generate && npx tsc",
    "prestart": "npm run build",
    "start": "node --experimental-loader newrelic/esm-loader.mjs dist/src/index.js",
    "preprod": "npm run build",
    "prod": "node dist/src/index.js",
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js --silent=false --detectOpenHandles",
    "predev": "npx prisma generate",
    "dev": "npx nodemon --no-warnings --exec 'node --loader ts-node/esm' src/index.ts",
    "codegen": "node --no-warnings --loader ts-node/esm src/graphql/codegen/codegen.ts && graphql-codegen-esm --config src/graphql/codegen/codegen.yml"
  },
  "prisma": {
    "seed": "node --no-warnings --loader ts-node/esm ./prisma/seeds/index.ts"
  },
  },
  "dependencies": {
    "@apollo/datasource-rest": "^4.3.2",
    "@apollo/server": "^4.3.0",
    "@newrelic/apollo-server-plugin": "^3.0.0",
    "@pothos/core": "^3.24.0",
    "@pothos/plugin-prisma": "^3.39.0",
    "@pothos/plugin-scope-auth": "^3.17.0",
    "@prisma/client": "^4.8.0",
    "@types/auth0": "^3.3.1",
    "auth0": "^3.3.0",
    "dotenv": "^16.0.3",
    "graphql": "^16.6.0",
    "graphql-scalars": "^1.20.1",
    "graphql-tag": "^2.12.6",
    "jsonwebtoken": "^9.0.0",
    "jwks-rsa": "^3.0.0",
    "lodash-es": "^4.17.21",
    "newrelic": "^9.15.0",
    "node-schedule": "^2.1.1"
  }```

**Comment by clarkClaim** [comment] 2023-04-18 19:19
Thanks so much for looking into this, and let me know if there is any additional information I can provide privately, without exposing our team's production code.

**Comment by bizob2828** [comment] 2023-04-18 19:21
Hi @clarkClaim sorry for the troubles.  A reproduction case would help our team better triage the issue you've logged, thanks!

**Comment by bizob2828** [comment] 2023-05-09 16:32
@clarkClaim I'm going to close this because we cannot reproduce.  If you can give us a reproduction case, please reopen.

**Closed by bizob2828** 2023-05-09 16:32 UTC
Labels: bug, needs-triage
